//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dropdownbind
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_state
    {
        public tbl_state()
        {
            this.tbl_city = new HashSet<tbl_city>();
        }
    
        public int id { get; set; }
        public string statename { get; set; }
    
        public virtual ICollection<tbl_city> tbl_city { get; set; }
    }
}
