//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allinone
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_rinkalEntities : DbContext
    {
        public db_rinkalEntities()
            : base("name=db_rinkalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_city> tbl_city { get; set; }
        public DbSet<tbl_state> tbl_state { get; set; }
        public DbSet<tbl_allinone> tbl_allinone { get; set; }
    }
}
