//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allinone
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_city
    {
        public int CID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> SID { get; set; }
    
        public virtual tbl_state tbl_state { get; set; }
    }
}
