//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("db_rajeshModel", "FK_tbl_state_tbl_country", "tbl_country", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(db_rajeshModel.tbl_country), "tbl_state", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(db_rajeshModel.tbl_state), true)]

#endregion

namespace db_rajeshModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class db_rajeshEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new db_rajeshEntities object using the connection string found in the 'db_rajeshEntities' section of the application configuration file.
        /// </summary>
        public db_rajeshEntities() : base("name=db_rajeshEntities", "db_rajeshEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db_rajeshEntities object.
        /// </summary>
        public db_rajeshEntities(string connectionString) : base(connectionString, "db_rajeshEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db_rajeshEntities object.
        /// </summary>
        public db_rajeshEntities(EntityConnection connection) : base(connection, "db_rajeshEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_country> tbl_country
        {
            get
            {
                if ((_tbl_country == null))
                {
                    _tbl_country = base.CreateObjectSet<tbl_country>("tbl_country");
                }
                return _tbl_country;
            }
        }
        private ObjectSet<tbl_country> _tbl_country;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_rajesh> tbl_rajesh
        {
            get
            {
                if ((_tbl_rajesh == null))
                {
                    _tbl_rajesh = base.CreateObjectSet<tbl_rajesh>("tbl_rajesh");
                }
                return _tbl_rajesh;
            }
        }
        private ObjectSet<tbl_rajesh> _tbl_rajesh;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_state> tbl_state
        {
            get
            {
                if ((_tbl_state == null))
                {
                    _tbl_state = base.CreateObjectSet<tbl_state>("tbl_state");
                }
                return _tbl_state;
            }
        }
        private ObjectSet<tbl_state> _tbl_state;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_country EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_country(tbl_country tbl_country)
        {
            base.AddObject("tbl_country", tbl_country);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_rajesh EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_rajesh(tbl_rajesh tbl_rajesh)
        {
            base.AddObject("tbl_rajesh", tbl_rajesh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_state EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_state(tbl_state tbl_state)
        {
            base.AddObject("tbl_state", tbl_state);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_rajeshModel", Name="tbl_country")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_country : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_country object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tbl_country Createtbl_country(global::System.Int32 id)
        {
            tbl_country tbl_country = new tbl_country();
            tbl_country.id = id;
            return tbl_country;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_rajeshModel", "FK_tbl_state_tbl_country", "tbl_state")]
        public EntityCollection<tbl_state> tbl_state
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_state>("db_rajeshModel.FK_tbl_state_tbl_country", "tbl_state");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_state>("db_rajeshModel.FK_tbl_state_tbl_country", "tbl_state", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_rajeshModel", Name="tbl_rajesh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_rajesh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_rajesh object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tbl_rajesh Createtbl_rajesh(global::System.Int32 id)
        {
            tbl_rajesh tbl_rajesh = new tbl_rajesh();
            tbl_rajesh.id = id;
            return tbl_rajesh;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fname
        {
            get
            {
                return _fname;
            }
            set
            {
                OnfnameChanging(value);
                ReportPropertyChanging("fname");
                _fname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fname");
                OnfnameChanged();
            }
        }
        private global::System.String _fname;
        partial void OnfnameChanging(global::System.String value);
        partial void OnfnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lname
        {
            get
            {
                return _lname;
            }
            set
            {
                OnlnameChanging(value);
                ReportPropertyChanging("lname");
                _lname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lname");
                OnlnameChanged();
            }
        }
        private global::System.String _lname;
        partial void OnlnameChanging(global::System.String value);
        partial void OnlnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_rajeshModel", Name="tbl_state")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_state : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_state object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tbl_state Createtbl_state(global::System.Int32 id)
        {
            tbl_state tbl_state = new tbl_state();
            tbl_state.id = id;
            return tbl_state;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cnid
        {
            get
            {
                return _cnid;
            }
            set
            {
                OncnidChanging(value);
                ReportPropertyChanging("cnid");
                _cnid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cnid");
                OncnidChanged();
            }
        }
        private Nullable<global::System.Int32> _cnid;
        partial void OncnidChanging(Nullable<global::System.Int32> value);
        partial void OncnidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_rajeshModel", "FK_tbl_state_tbl_country", "tbl_country")]
        public tbl_country tbl_country
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_country>("db_rajeshModel.FK_tbl_state_tbl_country", "tbl_country").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_country>("db_rajeshModel.FK_tbl_state_tbl_country", "tbl_country").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_country> tbl_countryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_country>("db_rajeshModel.FK_tbl_state_tbl_country", "tbl_country");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_country>("db_rajeshModel.FK_tbl_state_tbl_country", "tbl_country", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
