//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcexam
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int pid { get; set; }
        public string pname { get; set; }
        public Nullable<int> pcategory { get; set; }
        public Nullable<int> pprice { get; set; }
        public string pdetails { get; set; }
        public string pimg { get; set; }
    }
}
