//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ALL_Cntrl_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hobby
    {
        public int id { get; set; }
        public string hobby { get; set; }
    }
}
